name: Deployment

on:
  push:
    branches:
      - runnertest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run a script
        run: |
          echo "A push was made to the runnertest branch!"
